require('cursor-config')
require('settings')
require('packer-config')
require('colorschemes-config.onenord')
require('nvim-tree-config')
require('mappings')
require('mason-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('treesitter-config')
-- Close NvimTree if there is no other window
require('nvim-tree-config.autoclose')
